package pl.org.opi.sdsm.app.simplerepo.stru.editPhase.ui;

import javax.swing.DefaultListModel;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import lombok.Getter;
import pl.org.opi.sdsm.app.simplerepo.oper.editPhase.queries.op.SelectedFieldClearQryOp;
import pl.org.opi.sdsm.app.simplerepo.oper.editPhase.queries.op.SelectedFieldShowQryOp;
import pl.org.opi.sdsm.app.simplerepo.oper.editPhase.queries.uop.OnChosenDeselectedQryUop;
import pl.org.opi.sdsm.app.simplerepo.oper.editPhase.queries.uop.OnChosenSelectedQryUop;
import pl.org.opi.sdsm.app.simplerepo.oper.editPhase.queries.uop.OnResetTableToDefaultsQryUop;
import pl.org.opi.sdsm.app.simplerepo.oper.editPhase.queries.uop.OnSaveNameQryUop;
import pl.org.opi.sdsm.app.simplerepo.oper.editPhase.queries.uop.OnSaveTypeQryUop;
import pl.org.opi.sdsm.app.simplerepo.oper.editPhase.queries.uop.OnTabQrySelectedUop;
import pl.org.opi.sdsm.app.simplerepo.oper.editPhase.tables.op.SelectedFieldClearOp;
import pl.org.opi.sdsm.app.simplerepo.oper.editPhase.tables.op.SelectedFieldShowOp;
import pl.org.opi.sdsm.app.simplerepo.oper.editPhase.tables.uop.OnChosenDeselectedUop;
import pl.org.opi.sdsm.app.simplerepo.oper.editPhase.tables.uop.OnChosenSelectedUop;
import pl.org.opi.sdsm.app.simplerepo.oper.editPhase.tables.uop.OnResetTableToDefaultsUop;
import pl.org.opi.sdsm.app.simplerepo.oper.editPhase.tables.uop.OnSaveNameUop;
import pl.org.opi.sdsm.app.simplerepo.oper.editPhase.tables.uop.OnSaveTypeUop;
import pl.org.opi.sdsm.app.simplerepo.oper.editPhase.tables.uop.OnTabTablesSelectedUop;

@Getter
public class EditViewPanel extends javax.swing.JPanel {

    public EditViewPanel() {
        initComponents();
        initComponents2();
    }

    private final DefaultListModel<String> modelListChosenTables = new DefaultListModel<>();
    private final DefaultListModel<String> modelListChosenQ = new DefaultListModel<>();
    private final ColumnsTableEditModel modelTableTables = new ColumnsTableEditModel();
    private final ColumnsTableEditModel modelTableQueries = new ColumnsTableEditModel();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainTabbedPane = new javax.swing.JTabbedPane();
        panelTables = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listChosenTables = new javax.swing.JList<>();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        edJavaNameDefault = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        edJavaNameFinal = new javax.swing.JTextField();
        btnSaveJavaNameFinal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        edJavaTypeDefault = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        edJavaTypeFinal = new javax.swing.JTextField();
        btnSaveJavaTypeFinal = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableTable = new javax.swing.JTable();
        btnResetNames = new javax.swing.JButton();
        panelQueries = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        listChosenQ = new javax.swing.JList<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        taQrySql = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        btnResetNamesQ = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableQuery = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        edJavaNameDefaultQ = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        edJavaNameFinalQ = new javax.swing.JTextField();
        btnSaveJavaNameFinalQ = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        edJavaTypeDefaultQ = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        edJavaTypeFinalQ = new javax.swing.JTextField();
        btnSaveJavaTypeFinalQ = new javax.swing.JButton();

        mainTabbedPane.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                mainTabbedPaneStateChanged(evt);
            }
        });

        jLabel2.setText("Tables");

        listChosenTables.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(listChosenTables);

        jLabel13.setText("javaNameDefault");

        edJavaNameDefault.setEditable(false);

        jLabel14.setText("javaNameFinal");

        btnSaveJavaNameFinal.setText("Save name");
        btnSaveJavaNameFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveJavaNameFinalActionPerformed(evt);
            }
        });

        jLabel1.setText("javaTypeDefault");

        edJavaTypeDefault.setEditable(false);

        jLabel3.setText("javaTypeFinal");

        btnSaveJavaTypeFinal.setText("Save type");
        btnSaveJavaTypeFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveJavaTypeFinalActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edJavaNameDefault, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSaveJavaNameFinal)
                            .addComponent(edJavaNameFinal))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(edJavaTypeDefault, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                        .addComponent(edJavaTypeFinal))
                    .addComponent(btnSaveJavaTypeFinal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(edJavaNameDefault, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(edJavaTypeDefault, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(edJavaNameFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(edJavaTypeFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveJavaNameFinal)
                    .addComponent(btnSaveJavaTypeFinal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tableTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tableTable);

        btnResetNames.setText("Reset names/types to defaults");
        btnResetNames.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetNamesActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelTablesLayout = new javax.swing.GroupLayout(panelTables);
        panelTables.setLayout(panelTablesLayout);
        panelTablesLayout.setHorizontalGroup(
            panelTablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panelTablesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelTablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 942, Short.MAX_VALUE)
                    .addGroup(panelTablesLayout.createSequentialGroup()
                        .addGroup(panelTablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(btnResetNames)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panelTablesLayout.setVerticalGroup(
            panelTablesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTablesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnResetNames)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mainTabbedPane.addTab("Tables", panelTables);

        jLabel4.setText("Queries");

        listChosenQ.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(listChosenQ);

        taQrySql.setEditable(false);
        taQrySql.setColumns(20);
        taQrySql.setRows(5);
        jScrollPane4.setViewportView(taQrySql);

        jLabel5.setText("SQL select");

        btnResetNamesQ.setText("Reset names/types to defaults");
        btnResetNamesQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetNamesQActionPerformed(evt);
            }
        });

        tableQuery.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane5.setViewportView(tableQuery);

        jLabel15.setText("javaNameDefault");

        edJavaNameDefaultQ.setEditable(false);

        jLabel16.setText("javaNameFinal");

        btnSaveJavaNameFinalQ.setText("Save name");
        btnSaveJavaNameFinalQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveJavaNameFinalQActionPerformed(evt);
            }
        });

        jLabel6.setText("javaTypeDefault");

        edJavaTypeDefaultQ.setEditable(false);

        jLabel7.setText("javaTypeFinal");

        btnSaveJavaTypeFinalQ.setText("Save type");
        btnSaveJavaTypeFinalQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveJavaTypeFinalQActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edJavaNameDefaultQ, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnSaveJavaNameFinalQ)
                            .addComponent(edJavaNameFinalQ))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(edJavaTypeDefaultQ, javax.swing.GroupLayout.DEFAULT_SIZE, 333, Short.MAX_VALUE)
                        .addComponent(edJavaTypeFinalQ))
                    .addComponent(btnSaveJavaTypeFinalQ))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(edJavaNameDefaultQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(edJavaTypeDefaultQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(edJavaNameFinalQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(edJavaTypeFinalQ, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSaveJavaNameFinalQ)
                    .addComponent(btnSaveJavaTypeFinalQ))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout panelQueriesLayout = new javax.swing.GroupLayout(panelQueries);
        panelQueries.setLayout(panelQueriesLayout);
        panelQueriesLayout.setHorizontalGroup(
            panelQueriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQueriesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelQueriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelQueriesLayout.createSequentialGroup()
                        .addGroup(panelQueriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelQueriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelQueriesLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 536, Short.MAX_VALUE)))
                    .addGroup(panelQueriesLayout.createSequentialGroup()
                        .addComponent(btnResetNamesQ)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane5))
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        panelQueriesLayout.setVerticalGroup(
            panelQueriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelQueriesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelQueriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelQueriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnResetNamesQ)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        mainTabbedPane.addTab("Queries", panelQueries);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainTabbedPane)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mainTabbedPaneStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_mainTabbedPaneStateChanged
        int tabIndex = mainTabbedPane.getSelectedIndex();
        switch (tabIndex) {
            case 0:
                new OnTabTablesSelectedUop().exec(this);
                break;
            case 1:
                new OnTabQrySelectedUop().exec(this);
                break;
        }
    }//GEN-LAST:event_mainTabbedPaneStateChanged

    private void btnSaveJavaNameFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveJavaNameFinalActionPerformed
        new OnSaveNameUop(this).exec();
    }//GEN-LAST:event_btnSaveJavaNameFinalActionPerformed

    private void btnSaveJavaTypeFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveJavaTypeFinalActionPerformed
        new OnSaveTypeUop(this).exec();
    }//GEN-LAST:event_btnSaveJavaTypeFinalActionPerformed

    private void btnResetNamesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetNamesActionPerformed
        if (listChosenTables.getSelectedIndex() >= 0) {
            new OnResetTableToDefaultsUop().exec(this, listChosenTables.getSelectedValue());
        }
    }//GEN-LAST:event_btnResetNamesActionPerformed

    private void btnSaveJavaNameFinalQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveJavaNameFinalQActionPerformed
        new OnSaveNameQryUop(this).exec();
    }//GEN-LAST:event_btnSaveJavaNameFinalQActionPerformed

    private void btnSaveJavaTypeFinalQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveJavaTypeFinalQActionPerformed
        new OnSaveTypeQryUop(this).exec();
    }//GEN-LAST:event_btnSaveJavaTypeFinalQActionPerformed

    private void btnResetNamesQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetNamesQActionPerformed
        if (listChosenQ.getSelectedIndex() >= 0) {
            new OnResetTableToDefaultsQryUop().exec(this, listChosenQ.getSelectedValue());
        }
    }//GEN-LAST:event_btnResetNamesQActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnResetNames;
    private javax.swing.JButton btnResetNamesQ;
    private javax.swing.JButton btnSaveJavaNameFinal;
    private javax.swing.JButton btnSaveJavaNameFinalQ;
    private javax.swing.JButton btnSaveJavaTypeFinal;
    private javax.swing.JButton btnSaveJavaTypeFinalQ;
    private javax.swing.JTextField edJavaNameDefault;
    private javax.swing.JTextField edJavaNameDefaultQ;
    private javax.swing.JTextField edJavaNameFinal;
    private javax.swing.JTextField edJavaNameFinalQ;
    private javax.swing.JTextField edJavaTypeDefault;
    private javax.swing.JTextField edJavaTypeDefaultQ;
    private javax.swing.JTextField edJavaTypeFinal;
    private javax.swing.JTextField edJavaTypeFinalQ;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JList<String> listChosenQ;
    private javax.swing.JList<String> listChosenTables;
    private javax.swing.JTabbedPane mainTabbedPane;
    private javax.swing.JPanel panelQueries;
    private javax.swing.JPanel panelTables;
    private javax.swing.JTextArea taQrySql;
    private javax.swing.JTable tableQuery;
    private javax.swing.JTable tableTable;
    // End of variables declaration//GEN-END:variables

    private void initComponents2() {
        //
        listChosenTables.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        listChosenTables.setModel(modelListChosenTables);
        listChosenTables.getSelectionModel().addListSelectionListener((ListSelectionEvent event) -> {
            if (!event.getValueIsAdjusting()) {
                if (listChosenTables.getSelectedIndex() >= 0) {
                    new OnChosenSelectedUop().exec(this, listChosenTables.getSelectedValue());
                } else {
                    new OnChosenDeselectedUop().exec(this);
                }
            }
        });
        //
        tableTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tableTable.setModel(modelTableTables);
        tableTable.getSelectionModel().addListSelectionListener((ListSelectionEvent event) -> {
            if (!event.getValueIsAdjusting()) {
                if (tableTable.getSelectedRow() >= 0) {
                    new SelectedFieldShowOp(this).exec();
                } else {
                    new SelectedFieldClearOp(this).exec();
                }
            }
        });
        //////
        listChosenQ.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        listChosenQ.setModel(modelListChosenQ);
        listChosenQ.getSelectionModel().addListSelectionListener((ListSelectionEvent event) -> {
            if (!event.getValueIsAdjusting()) {
                if (listChosenQ.getSelectedIndex() >= 0) {
                    new OnChosenSelectedQryUop().exec(this, listChosenQ.getSelectedValue());
                } else {
                    new OnChosenDeselectedQryUop().exec(this);
                }
            }
        });
        //
        tableQuery.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        tableQuery.setModel(modelTableQueries);
        tableQuery.getSelectionModel().addListSelectionListener((ListSelectionEvent event) -> {
            if (!event.getValueIsAdjusting()) {
                if (tableQuery.getSelectedRow() >= 0) {
                    new SelectedFieldShowQryOp(this).exec();
                } else {
                    new SelectedFieldClearQryOp(this).exec();
                }
            }
        });
        //
    }

}
